version: "3.1"
services:
  php:
     build: './IaC/php/'
     volumes:
       - ./:/var/www/html/
  apache:
    build: './IaC/apache/'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html/
volumes:
    db_data: {}

